version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx/conf/production-nginx.conf:/etc/nginx/nginx.conf
            - ./build/:/var/www/contact-build
            - ./nginx/cache/:/etc/nginx/cache
            - ./contact_data/logs/nginx/:/var/log/nginx
        ports:
            - "80:80"
        networks:
            - contact

networks:
    contact:
        driver: bridge